CREATE TABLE usuarios(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
	usuario VARCHAR(120) NOT NULL,
    clave VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
)ENGINE = InnoDB;

